// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzRrZLE9nKSNVdxtg-Wkebx5StnC9RnE0',
    appId: '1:1022946742871:web:e1a0b306e613de638d8912',
    messagingSenderId: '1022946742871',
    projectId: 'studytogether-ff930',
    authDomain: 'studytogether-ff930.firebaseapp.com',
    storageBucket: 'studytogether-ff930.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdN9tjbLaQJoxlDNIE6C8VIArma2TCLnA',
    appId: '1:1022946742871:android:661e53a36bfb37818d8912',
    messagingSenderId: '1022946742871',
    projectId: 'studytogether-ff930',
    storageBucket: 'studytogether-ff930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfSwff2bRnRO94bxjb4oK214yq4JIjeX4',
    appId: '1:1022946742871:ios:7308f5d2bf6fe57f8d8912',
    messagingSenderId: '1022946742871',
    projectId: 'studytogether-ff930',
    storageBucket: 'studytogether-ff930.appspot.com',
    iosBundleId: 'com.example.studytogether5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfSwff2bRnRO94bxjb4oK214yq4JIjeX4',
    appId: '1:1022946742871:ios:198e270636738da08d8912',
    messagingSenderId: '1022946742871',
    projectId: 'studytogether-ff930',
    storageBucket: 'studytogether-ff930.appspot.com',
    iosBundleId: 'com.example.studytogether5.RunnerTests',
  );
}
